import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | Cognis",
  description: "Terms and conditions for the Cognis financial engagement platform.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing or using the Cognis platform, you agree to be bound by these Terms and Conditions. If you do not agree, you may not use the platform. These terms apply to all users, including banks, fintech teams, and authorised administrators.`,
  },
  {
    title: "2. Platform Description",
    body: `Cognis is a real-time financial engagement engine that detects customer money moments, determines the next best action, and delivers context-aware guidance through approved channels. The platform operates as a service integrated into the bank's existing systems.`,
  },
  {
    title: "3. Permitted Use",
    body: `The platform may only be used for its intended purpose: analysing banking events and delivering compliant customer engagement. You may not reverse-engineer, resell, or redistribute the platform or its outputs. All use must comply with applicable banking regulations, including RBI guidelines.`,
  },
  {
    title: "4. Data Responsibilities",
    body: `Each participating bank remains the data controller for its customer information. Cognis acts as a data processor under the bank's direction. Banks are responsible for obtaining necessary customer consents and ensuring lawful basis for data processing.`,
  },
  {
    title: "5. Compliance and Guardrails",
    body: `Every action generated by Cognis passes through compliance checks including eligibility, consent, frequency caps, and regulatory guardrails. However, the bank retains final responsibility for all customer-facing communications and actions taken through the platform.`,
  },
  {
    title: "6. Service Availability",
    body: `Cognis is designed for high availability but does not guarantee uninterrupted service. Scheduled maintenance windows and emergency fixes may temporarily affect availability. We will communicate planned downtime through the admin console in advance.`,
  },
  {
    title: "7. Limitation of Liability",
    body: `Cognis provides decision support, not financial advice. The platform's outputs are recommendations that must be validated by the bank's own compliance and risk processes. Cognis is not liable for losses arising from reliance on automated recommendations without appropriate human oversight.`,
  },
  {
    title: "8. Intellectual Property",
    body: `All intellectual property in the Cognis platform, including its architecture, agent framework, and decision logic, remains the property of the platform developers. Banks retain full ownership of their customer data and generated insights specific to their portfolio.`,
  },
  {
    title: "9. Modifications",
    body: `We reserve the right to modify these terms at any time. Continued use of the platform after changes are communicated constitutes acceptance of the updated terms. Material changes will be flagged through the admin console with a reasonable notice period.`,
  },
  {
    title: "10. Governing Law",
    body: `These terms are governed by the laws of India. Any disputes arising from the use of the platform shall be subject to the exclusive jurisdiction of the courts in the applicable jurisdiction.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f1ece8] text-[#322c2b]">
      <nav className="fixed inset-x-0 top-0 z-50 flex justify-center pt-[clamp(12px,1.05vw,20px)]">
        <Link
          href="/"
          className="flex h-[clamp(50px,3.55vw,68px)] items-center gap-3 rounded-full bg-white px-8 text-[clamp(15px,1.03vw,19px)] font-semibold tracking-[-0.02em] text-[#322c2b] transition-opacity hover:opacity-75"
        >
          <span className="h-2 w-2 bg-[#827367]" />
          Cognis
        </Link>
      </nav>

      <main className="mx-auto max-w-[780px] px-5 pt-[160px] pb-[180px]">
        <h1 className="text-[clamp(36px,3.2vw,56px)] font-semibold leading-[1.02] tracking-[-0.05em] text-black">
          Terms &amp; Conditions
        </h1>
        <p className="mt-4 text-[15px] leading-[1.32] tracking-[-0.02em] text-[#827367]">
          Effective date: June 2026
        </p>

        <div className="mt-[56px] space-y-[52px]">
          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-[clamp(20px,1.4vw,26px)] font-semibold leading-[1.1] tracking-[-0.035em] text-black">
                {section.title}
              </h2>
              <p className="mt-4 text-[clamp(15px,0.95vw,17px)] leading-[1.55] tracking-[-0.01em] text-[#4a4a4a]">
                {section.body}
              </p>
            </section>
          ))}
        </div>

        <div className="mt-[72px] h-px w-full bg-[#c6b8ae]" />

        <Link
          href="/"
          className="mt-8 inline-flex items-center gap-2 text-[15px] font-medium tracking-[-0.02em] text-[#827367] transition-colors hover:text-[#322c2b]"
        >
          <span>&larr;</span> Back to Cognis
        </Link>
      </main>

      <footer className="bg-[#322c2b] px-5 py-10 text-center">
        <p className="text-[15px] leading-none tracking-[-0.03em] text-[#827367]">
          Cognis 2026
        </p>
      </footer>
    </div>
  );
}
